<?php

return [

    'tree' => [
        'label'                => 'Tree',
        'emoji'                => '🌳',
        'color'                => '#166534',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['tree_type'],
        'optional_meta'        => ['variety', 'latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'meta_options'         => [
            'tree_type' => [
                'olive', 'almond', 'fig', 'carob', 'lemon', 'orange', 'mandarin',
                'pistachio', 'pomegranate', 'cherry', 'prickly_pear', 'peach',
                'apricot', 'mulberry', 'hazelnut', 'walnut', 'medlar', 'vine', 'other',
            ],
        ],
        'harvest_enabled'      => true,
        'harvest_max_per_year' => 1,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'olive_tree' => [
        'label'                => 'Olive Tree',
        'emoji'                => '🫒',
        'color'                => '#2d6a4f',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'harvest_max_per_year' => 1,
        'finance_enabled'      => true,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'almond_tree' => [
        'label'                => 'Almond Tree',
        'emoji'                => '🌰',
        'color'                => '#92400e',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'harvest_max_per_year' => 1,
        'finance_enabled'      => true,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'vine' => [
        'label'                => 'Vine',
        'emoji'                => '🍇',
        'color'                => '#6d28d9',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'harvest_max_per_year' => 1,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder'],
    ],

    'garden' => [
        'label'                => 'Garden',
        'emoji'                => '🌿',
        'color'                => '#0369a1',
        'hidden_from_create'   => true,
        'allowed_parents'      => [null],
        'allowed_children'     => ['bed'],
        'required_meta'        => [],
        'optional_meta'        => ['garden_area_m2', 'soil_type', 'sun_exposure', 'irrigation_type'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['amendment', 'note'],
        'attachment_categories'=> ['identification_photo', 'general_attachment'],
        'reminder_presets'     => [],
    ],

    'bed' => [
        'label'                => 'Garden Bed',
        'emoji'                => '🌱',
        'color'                => '#0369a1',
        'allowed_parents'      => ['garden', null],
        'allowed_children'     => ['line'],
        'required_meta'        => [],
        'optional_meta'        => ['irrigation_type', 'soil_type'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'boundary_enabled'     => true,
        'action_types'         => ['amendment', 'note', 'planting'],
        'attachment_categories'=> ['identification_photo', 'general_attachment'],
        'reminder_presets'     => [],
    ],

    'line' => [
        'label'                => 'Line',
        'emoji'                => '〰️',
        'color'                => '#1d4ed8',
        'hidden_from_create'   => true,
        'allowed_parents'      => ['bed'],
        'allowed_children'     => [],
        'required_meta'        => [],
        'optional_meta'        => ['line_crop_mix', 'cover_crop_type'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['planting', 'harvest', 'note'],
        'attachment_categories'=> ['identification_photo', 'general_attachment'],
        'reminder_presets'     => [],
    ],

    'prep_zone' => [
        'label'                => 'Prep Zone',
        'emoji'                => '🟫',
        'color'                => '#b45309',
        'allowed_parents'      => [null],
        'allowed_children'     => [],
        'required_meta'        => [],
        'optional_meta'        => ['cover_crop_type', 'prep_type'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['amendment', 'note', 'conversion'],
        'attachment_categories'=> ['identification_photo', 'general_attachment'],
        'reminder_presets'     => ['readiness_reminder'],
    ],

    'mobile_coop' => [
        'label'                => 'Mobile Coop',
        'emoji'                => '🐓',
        'color'                => '#991b1b',
        'allowed_parents'      => [null],
        'allowed_children'     => [],
        'required_meta'        => [],
        'optional_meta'        => ['mobile_asset_history_enabled'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => true,
        'action_types'         => ['move', 'note'],
        'attachment_categories'=> ['identification_photo', 'general_attachment'],
        'reminder_presets'     => ['move_reminder'],
    ],

    'building' => [
        'label'                => 'Building',
        'emoji'                => '🏠',
        'color'                => '#374151',
        'allowed_parents'      => [null],
        'allowed_children'     => [],
        'required_meta'        => [],
        'optional_meta'        => ['purpose'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['maintenance', 'note'],
        'attachment_categories'=> ['identification_photo', 'general_attachment'],
        'reminder_presets'     => ['maintenance_reminder'],
    ],

    'water_point' => [
        'label'                => 'Water Point',
        'emoji'                => '💧',
        'color'                => '#0284c7',
        'allowed_parents'      => [null],
        'allowed_children'     => [],
        'required_meta'        => [],
        'optional_meta'        => ['purpose'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['maintenance', 'note'],
        'attachment_categories'=> ['identification_photo', 'general_attachment'],
        'reminder_presets'     => ['maintenance_reminder'],
    ],

    'zone' => [
        'label'                => 'Zone',
        'allowed_parents'      => [null],
        'allowed_children'     => [],
        'required_meta'        => [],
        'optional_meta'        => ['purpose'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['note'],
        'attachment_categories'=> ['identification_photo', 'general_attachment'],
        'reminder_presets'     => [],
    ],

    'orchard' => [
        'label'                => 'Orchard',
        'allowed_parents'      => [null],
        'allowed_children'     => ['tree', 'olive_tree', 'almond_tree', 'vine'],
        'required_meta'        => [],
        'optional_meta'        => ['garden_area_m2', 'purpose'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['note'],
        'attachment_categories'=> ['identification_photo', 'general_attachment'],
        'reminder_presets'     => [],
    ],

];
