<?php

return [

    'tree' => [
        'label'                => 'Tree',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'image_refresh_reminder'],
    ],

    'olive_tree' => [
        'label'                => 'Olive Tree',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'finance_enabled'      => true,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'almond_tree' => [
        'label'                => 'Almond Tree',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'finance_enabled'      => true,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'vine' => [
        'label'                => 'Vine',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder'],
    ],

    'fig_tree' => [
        'label'                => 'Fig Tree',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'carob_tree' => [
        'label'                => 'Carob Tree',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'lemon_tree' => [
        'label'                => 'Lemon Tree',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'finance_enabled'      => true,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'orange_tree' => [
        'label'                => 'Orange Tree',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'finance_enabled'      => true,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'mandarin_tree' => [
        'label'                => 'Mandarin Tree',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'pistachio_tree' => [
        'label'                => 'Pistachio Tree',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'finance_enabled'      => true,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'pomegranate_tree' => [
        'label'                => 'Pomegranate Tree',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'cherry_tree' => [
        'label'                => 'Cherry Tree',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'prickly_pear' => [
        'label'                => 'Prickly Pear',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'peach_tree' => [
        'label'                => 'Peach Tree',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'apricot_tree' => [
        'label'                => 'Apricot Tree',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'mulberry_tree' => [
        'label'                => 'Mulberry Tree',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'hazelnut_tree' => [
        'label'                => 'Hazelnut Tree',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'walnut_tree' => [
        'label'                => 'Walnut Tree',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'medlar_tree' => [
        'label'                => 'Medlar Tree',
        'allowed_parents'      => ['orchard', null],
        'allowed_children'     => [],
        'required_meta'        => ['variety'],
        'optional_meta'        => ['latin_name', 'estimated_age_years', 'purpose', 'sun_exposure', 'soil_type', 'irrigation_type'],
        'harvest_enabled'      => true,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['pruning', 'treatment', 'amendment', 'harvest', 'image_refresh', 'note'],
        'attachment_categories'=> ['identification_photo', 'yearly_refresh_north', 'yearly_refresh_south', 'yearly_refresh_east', 'yearly_refresh_west', 'generated_icon', 'harvest_photo'],
        'reminder_presets'     => ['pruning_reminder', 'treatment_reminder', 'harvest_reminder', 'image_refresh_reminder'],
    ],

    'garden' => [
        'label'                => 'Garden',
        'allowed_parents'      => [null],
        'allowed_children'     => ['bed'],
        'required_meta'        => [],
        'optional_meta'        => ['garden_area_m2', 'soil_type', 'sun_exposure', 'irrigation_type'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['amendment', 'note'],
        'attachment_categories'=> ['identification_photo', 'general_attachment'],
        'reminder_presets'     => [],
    ],

    'bed' => [
        'label'                => 'Bed',
        'allowed_parents'      => ['garden'],
        'allowed_children'     => ['line'],
        'required_meta'        => [],
        'optional_meta'        => ['bed_length_m', 'bed_width_m', 'irrigation_type', 'soil_type'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'boundary_enabled'     => true,
        'action_types'         => ['amendment', 'note', 'planting'],
        'attachment_categories'=> ['identification_photo', 'general_attachment'],
        'reminder_presets'     => [],
    ],

    'line' => [
        'label'                => 'Line',
        'allowed_parents'      => ['bed'],
        'allowed_children'     => [],
        'required_meta'        => [],
        'optional_meta'        => ['line_crop_mix', 'cover_crop_type'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['planting', 'harvest', 'note'],
        'attachment_categories'=> ['identification_photo', 'general_attachment'],
        'reminder_presets'     => [],
    ],

    'prep_zone' => [
        'label'                => 'Prep Zone',
        'allowed_parents'      => [null],
        'allowed_children'     => [],
        'required_meta'        => [],
        'optional_meta'        => ['cover_crop_type', 'prep_type'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['amendment', 'note', 'conversion'],
        'attachment_categories'=> ['identification_photo', 'general_attachment'],
        'reminder_presets'     => ['readiness_reminder'],
    ],

    'mobile_coop' => [
        'label'                => 'Mobile Coop',
        'allowed_parents'      => [null],
        'allowed_children'     => [],
        'required_meta'        => [],
        'optional_meta'        => ['mobile_asset_history_enabled'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => true,
        'action_types'         => ['move', 'note'],
        'attachment_categories'=> ['identification_photo', 'general_attachment'],
        'reminder_presets'     => ['move_reminder'],
    ],

    'building' => [
        'label'                => 'Building',
        'allowed_parents'      => [null],
        'allowed_children'     => [],
        'required_meta'        => [],
        'optional_meta'        => ['purpose'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['maintenance', 'note'],
        'attachment_categories'=> ['identification_photo', 'general_attachment'],
        'reminder_presets'     => ['maintenance_reminder'],
    ],

    'water_point' => [
        'label'                => 'Water Point',
        'allowed_parents'      => [null],
        'allowed_children'     => [],
        'required_meta'        => [],
        'optional_meta'        => ['purpose'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['maintenance', 'note'],
        'attachment_categories'=> ['identification_photo', 'general_attachment'],
        'reminder_presets'     => ['maintenance_reminder'],
    ],

    'zone' => [
        'label'                => 'Zone',
        'allowed_parents'      => [null],
        'allowed_children'     => [],
        'required_meta'        => [],
        'optional_meta'        => ['purpose'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['note'],
        'attachment_categories'=> ['identification_photo', 'general_attachment'],
        'reminder_presets'     => [],
    ],

    'orchard' => [
        'label'                => 'Orchard',
        'allowed_parents'      => [null],
        'allowed_children'     => ['tree', 'olive_tree', 'almond_tree', 'vine', 'fig_tree', 'carob_tree', 'lemon_tree', 'orange_tree', 'mandarin_tree', 'pistachio_tree', 'pomegranate_tree', 'cherry_tree', 'prickly_pear', 'peach_tree', 'apricot_tree', 'mulberry_tree', 'hazelnut_tree', 'walnut_tree', 'medlar_tree'],
        'required_meta'        => [],
        'optional_meta'        => ['garden_area_m2', 'purpose'],
        'harvest_enabled'      => false,
        'finance_enabled'      => false,
        'mobile_asset'         => false,
        'action_types'         => ['note'],
        'attachment_categories'=> ['identification_photo', 'general_attachment'],
        'reminder_presets'     => [],
    ],

];
